name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest

      - name: Запустить тесты
        run: pytest
